### PR TITLE
Feature/button complete timeout

### PR DESCRIPTION
**Pull request by rehazler**
This branch implements a function that handles button event listeners and disables the buttons after a 3 second delay. If the user clicks the button again, the button deactivation is canceled. If the 3 seconds has elapsed then the button is deactivated and a block icon is placed over the button. If the user clicks on the blocked button again they will be informed that if they proceed then the task will be marked incomplete. (From there we will need to subtract any points that were given.) If they proceed then the button will be reactivated and the blocked icon will disappear.

### CODE REVIEW

**Comment by bitmogram** [comment]
Everything looks good as far as I can tell.

**Review by anthony61016 — APPROVED** [review]
looks pretty good no issues to my naked eye

**Review by bitmogram — APPROVED** [review]
Everything looks great!

**Review by jacob-rachal — APPROVED** [review]
I don't see anything wrong, or too horribly eye-meltingly bad.

**Pull request merged**
